services:
  postgres:
    image: postgres:17-alpine
    container_name: jobflow-postgres

    environment:
      POSTGRES_USER: jobflow
      POSTGRES_PASSWORD: jobflow
      POSTGRES_DB: jobflow

    ports:
      - "5433:5432"

    volumes:
      - jobflow_postgres_data:/var/lib/postgresql/data

volumes:
  jobflow_postgres_data: